import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My Cv</title>
        <meta name="description" content="Generated by Dat" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <div className={styles.left}>
            <div className={styles.pic}>
              <img src="anh the.jpg" alt="" />
              <div className={styles.name}>
                <p>Cao Tiến Đạt</p>
              </div>
            </div>
            <div className={styles.target}>
              <h2>Thông tin cá nhân</h2>
              <div className={styles.infoValue}>
                <p>Email</p>
                <p>tiendat772001@gmail.com</p>
              </div>
              <div className={styles.infoValue}>
                <p>Số điện thoại</p>
                <p>0975804410</p>
              </div>

              <div className={styles.infoValue}>
                <p>Nơi ở</p>
                <p>Đống Đa, Hà Nội</p>
              </div>

              <div className={styles.infoValue}>
                <p>Ngày sinh</p>
                <p>07/07/2001</p>
              </div>
            </div>

            <div className={styles.target}>
              <h2>Kĩ năng</h2>
              <p> - HTML5</p>
              <p> - JAVASCRIPT</p>
              <p> - CSS3</p>
              <p> - REACTJS ( REACT HOOK FORM , ANT DESIGN, NEXTJS )</p>
              <p> - TAILWIND CSS</p>
              <p> - RESPONSIVE WEB DESIGN</p>
            </div>

            <div className={styles.target}>
              <h2>Sở thích</h2>
              <p> - Nghe nhạc</p>
              <p> - Chơi game </p>
              <p> - Tìm hiểu về đồ công nghệ </p>
              <p> - Xem phim</p>
            </div>

            <div className={styles.target}>
              <h2>Blog</h2>
              <p>
                <a href="https://techmaster.vn/preview/posts/37342/react-hooks-su-dung-usecontext-va-usereducer-de-thay-the-redux">
                  - Cách sử dụng useContext và useReduce
                </a>
              </p>
              <p>
                {" "}
                <a href="https://techmaster.vn/preview/posts/37364/mot-so-phuong-thuc-mang-huu-ich-trong-es6-javascript">
                  - Một số phương thức mảng hữu ích trong ES6 JavaScript
                </a>
              </p>
              <p>
                <a href="https://techmaster.vn/preview/posts/37519/tim-hieu-ve-nextjs">
                  {" "}
                  - Tìm hiểu về NextJs{" "}
                </a>
              </p>
              <p>
                <a href="https://techmaster.vn/preview/posts/37520/tim-hieu-async-await">
                  {" "}
                  - Tìm hiểu Async/Await
                </a>
              </p>

              <p>
                <a href="https://techmaster.vn/preview/posts/37521/sass-va-scss">
                  {" "}
                  - Sass và Scss
                </a>
              </p>
            </div>
          </div>

          <div className={styles.right}>
            <div className={styles.target}>
              <h2>Mục tiêu nghề nghiệp</h2>
              <p>
                Trở thành lập trình viên web front end + React.js chuyên nghiệp
                trong vòng 3 năm tới
              </p>
            </div>

            <div className={styles.target}>
              <h2>Học vấn</h2>

              <p>- Cao đẳng nghề Bách Khoa Hà Nội</p>
              <p>
                - Tốt nghiệp khóa đào tạo lập trình viên web front end + React
                tại Techmaster 3/2023
              </p>
            </div>

            <div className={styles.target}>
              <h2>Kinh nghiệm làm việc</h2>
              <p> - Hoàn thành 150 bài leetcode</p>
              <img className={styles.leetCode} src="leetcode.png" alt="" />
              <p style={{ paddingTop: "5px" }}>
                - Link leetcode:{" "}
                <a
                  style={{ color: "blue" }}
                  href="https://leetcode.com/tiendat772001/"
                >
                  https://leetcode.com/tiendat772001/
                </a>
              </p>
              <p>- Project cá nhân : Web bán đồ nội thất </p>
              <p>
                - Thiết kế lấy từ{" "}
                <a
                  style={{ color: "blue" }}
                  href="https://cuthbert.qodeinteractive.com/"
                >
                  https://cuthbert.qodeinteractive.com/
                </a>
              </p>
              <p>
                - Github :{" "}
                <a
                  style={{ color: "blue" }}
                  href="https://github.com/CaoDat77/game"
                >
                  https://github.com/CaoDat77/game
                </a>
              </p>

              <p>
                - Live :{" "}
                <a
                  style={{ color: "blue" }}
                  href="https://game-one-gamma.vercel.app/"
                >
                  https://game-one-gamma.vercel.app/
                </a>
              </p>

              <div className={styles.thumbnail}>
                <div>
                  <img src="pic-1.png" alt="" />
                </div>

                <div>
                  <img src="pic-2.png" alt="" />
                </div>
                <div>
                  <img src="pic-5.png" alt="" />
                </div>

                <div>
                  <img src="pic-4.png" alt="" />
                </div>
              </div>

              <div
                style={{
                  marginTop: "20px",
                  paddingLeft: "20px",
                }}
              >
                <p style={{ fontWeight: "bold" }}>Mô tả :</p>
                <div style={{ paddingLeft: "20px" }}>
                  <p>
                    {" "}
                    - Đăng ký, đăng nhập và lưu dữ liệu người dùng vào database
                    (Firebase).
                  </p>

                  <p> - Xem chi tiết sản phẩm</p>
                  <p> - Phân lọc sản phẩm danh mục</p>
                  <p> - Sắp xếp sản phẩm theo giá</p>
                  <p> - Tìm kiếm sản phẩm</p>
                  <p> - Phân trang</p>
                  <p>
                    {" "}
                    - Thêm, xóa sản phẩm vào giỏ hàng theo dữ liệu người dùng
                  </p>
                  <p> - Responsive trên nhiều màn hình</p>
                  <p> - Deployment sử dụng vercel </p>
                </div>
              </div>

              <div
                style={{
                  marginTop: "20px",
                  paddingLeft: "20px",
                }}
              >
                <p style={{ fontWeight: "bold" }}>Công nghệ sử dụng: </p>
                <div style={{ paddingLeft: "20px" }}>
                  <p> - HTML , module CSS</p>
                  <p> - ReactJs,Redux Toolkit</p>
                  <p> - React hook form</p>
                  <p> - NextJs</p>
                  <p> - MockAPI:mock.io</p>
                  <p> - FireBase</p>
                  <p> - Swiper Slider</p>
                  <p> - MUI</p>
                  <p> - React Bootsrap</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
